MEME_TEMPLATES = {
    "happy": [
        {
            "id": "drake-approve",
            "name": "Drake Approving",
            "emoji": "👏",
            "color": "#FFD700",
            "bg_gradient": "135deg, #1a1200 0%, #2d2000 100%",
            "accent": "#FFD700",
        },
        {
            "id": "doge",
            "name": "Doge",
            "emoji": "🐕",
            "color": "#F4E04D",
            "bg_gradient": "135deg, #0a0a1a 0%, #12122e 100%",
            "accent": "#F4E04D",
        },
        {
            "id": "success-kid",
            "name": "Success Kid",
            "emoji": "✊",
            "color": "#00FF88",
            "bg_gradient": "135deg, #001a0d 0%, #003320 100%",
            "accent": "#00FF88",
        },
        {
            "id": "happy-cat",
            "name": "Happy Cat",
            "emoji": "😸",
            "color": "#FF69B4",
            "bg_gradient": "135deg, #1a001a 0%, #2d002d 100%",
            "accent": "#FF69B4",
        },
    ],
    "surprised": [
        {
            "id": "surprised-pikachu",
            "name": "Surprised Pikachu",
            "emoji": "⚡😱",
            "color": "#FFD700",
            "bg_gradient": "135deg, #1a1500 0%, #2d2300 100%",
            "accent": "#FFD700",
        },
        {
            "id": "blinking-guy",
            "name": "Blinking Guy",
            "emoji": "👁️",
            "color": "#87CEEB",
            "bg_gradient": "135deg, #001a2b 0%, #00253d 100%",
            "accent": "#87CEEB",
        },
        {
            "id": "mind-blown",
            "name": "Mind Blown",
            "emoji": "🤯",
            "color": "#FF69B4",
            "bg_gradient": "135deg, #1a0010 0%, #2d0020 100%",
            "accent": "#FF69B4",
        },
        {
            "id": "galaxy-brain",
            "name": "Galaxy Brain",
            "emoji": "🧠✨",
            "color": "#9B59B6",
            "bg_gradient": "135deg, #0d001a 0%, #1a002d 100%",
            "accent": "#9B59B6",
        },
    ],
    "sad": [
        {
            "id": "crying-jordan",
            "name": "Crying Jordan",
            "emoji": "😭",
            "color": "#4169E1",
            "bg_gradient": "135deg, #000a1a 0%, #001020 100%",
            "accent": "#4169E1",
        },
        {
            "id": "sad-keanu",
            "name": "Sad Keanu",
            "emoji": "🪨",
            "color": "#808080",
            "bg_gradient": "135deg, #0a0a0a 0%, #141414 100%",
            "accent": "#808080",
        },
        {
            "id": "this-is-fine",
            "name": "This Is Fine",
            "emoji": "☕🔥",
            "color": "#FF6B35",
            "bg_gradient": "135deg, #1a0800 0%, #2d1000 100%",
            "accent": "#FF6B35",
        },
        {
            "id": "hide-the-pain",
            "name": "Hide The Pain Harold",
            "emoji": "😬",
            "color": "#DEB887",
            "bg_gradient": "135deg, #1a1000 0%, #2d1f00 100%",
            "accent": "#DEB887",
        },
    ],
    "angry": [
        {
            "id": "gordon-ramsay",
            "name": "Gordon Ramsay",
            "emoji": "👨‍🍳😤",
            "color": "#DC143C",
            "bg_gradient": "135deg, #1a0000 0%, #2d0000 100%",
            "accent": "#DC143C",
        },
        {
            "id": "table-flip",
            "name": "Table Flip",
            "emoji": "🗓️💢",
            "color": "#FF4500",
            "bg_gradient": "135deg, #1a0500 0%, #2d0800 100%",
            "accent": "#FF4500",
        },
        {
            "id": "angry-walter",
            "name": "Angry Walter",
            "emoji": "🎲🔥",
            "color": "#FF6600",
            "bg_gradient": "135deg, #1a0800 0%, #2d1000 100%",
            "accent": "#FF6600",
        },
    ],
    "disgusted": [
        {
            "id": "no-dog",
            "name": "No No No Dog",
            "emoji": "🙅🐕",
            "color": "#556B2F",
            "bg_gradient": "135deg, #0a0d00 0%, #141a00 100%",
            "accent": "#556B2F",
        },
        {
            "id": "eww",
            "name": "EWW",
            "emoji": "🤢",
            "color": "#6B8E23",
            "bg_gradient": "135deg, #050d00 0%, #0a1400 100%",
            "accent": "#6B8E23",
        },
        {
            "id": "side-eye-chloe",
            "name": "Side Eye Chloe",
            "emoji": "👀",
            "color": "#D4AF37",
            "bg_gradient": "135deg, #1a1500 0%, #2d2300 100%",
            "accent": "#D4AF37",
        },
    ],
    "fearful": [
        {
            "id": "scared-shaggy",
            "name": "Ultra Instinct Shaggy",
            "emoji": "👻😨",
            "color": "#9370DB",
            "bg_gradient": "135deg, #0d001a 0%, #1a002d 100%",
            "accent": "#9370DB",
        },
        {
            "id": "anxiety-meme",
            "name": "Anxiety Dog",
            "emoji": "🐕🔥",
            "color": "#FF4500",
            "bg_gradient": "135deg, #1a0500 0%, #2d0800 100%",
            "accent": "#FF4500",
        },
        {
            "id": "pepe-sweat",
            "name": "Sweaty Pepe",
            "emoji": "😰💦",
            "color": "#00CED1",
            "bg_gradient": "135deg, #001a1a 0%, #002d2d 100%",
            "accent": "#00CED1",
        },
    ],
    "neutral": [
        {
            "id": "stonks",
            "name": "Stonks",
            "emoji": "📈",
            "color": "#00FF88",
            "bg_gradient": "135deg, #001a0d 0%, #003320 100%",
            "accent": "#00FF88",
        },
        {
            "id": "it-is-what-it-is",
            "name": "It Is What It Is",
            "emoji": "🤷",
            "color": "#708090",
            "bg_gradient": "135deg, #0d0d0d 0%, #1a1a1a 100%",
            "accent": "#708090",
        },
        {
            "id": "big-brain",
            "name": "Big Brain",
            "emoji": "🧠",
            "color": "#9370DB",
            "bg_gradient": "135deg, #0d001a 0%, #1a002d 100%",
            "accent": "#9370DB",
        },
        {
            "id": "chad",
            "name": "Chad",
            "emoji": "😎",
            "color": "#C0C0C0",
            "bg_gradient": "135deg, #0a0a0a 0%, #1a1a1a 100%",
            "accent": "#C0C0C0",
        },
    ],
}

INTENSITY_THRESHOLDS = {
    "mild": {"streak_multiplier": 1, "font_scale": 1.0},
    "moderate": {"streak_multiplier": 2, "font_scale": 1.15},
    "strong": {"streak_multiplier": 3, "font_scale": 1.3},
}
